### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by bryevdv** [zjffdu/bkzep#1]
@zjffdu I would not do this

```
def output_zeppelin():
    output_notebook(notebook_type='zeppelin')
    install_notebook_hook('zeppelin', partial(load_notebook, notebook_type='zeppelin'),
                          _show_zeppelin_doc_with_state, _show_zeppelin_app_with_state, overwrite=True)
```

I would suggest this instead:
```
install_notebook_hook('zeppelin', 
                      YOUR_OWN_LOAD_FUNCTION_BZKEP_HERE
                     _show_zeppelin_doc_with_state, 
                     _show_zeppelin_app_with_state, 
                     overwrite=True)
```

Then users can just do `output_notebook(notebook_type='zeppelin')` (i.e. no need for an `output_zeppelin`. basically,  you should:

* not rely on `output_notebook(notebook_type='zeppelin')` *inside* this repo, the idea is that that code currently built into bokeh specialized to zeppelin will be removed so every thing can be maintained her in one place. `output_notebook(notebook_type='zeppelin')` only works without "installing" because I left the current code in place until you can publish a better replacement here. But this repo should not rely on the code I left temporarily. 

  *After* you run `install_notebook_hook`, that is what will ultimately make `output_notebook(notebook_type='zeppelin')` "just work" for users. 

* Also not rely on `partial(load_notebook, notebook_type='zeppelin')` i.e. you should make a function *here* that does what that code does, then install *that*

**Comment by zjffdu** [comment]
@bryevdv I guess you will remove the parameter `notebook_type` in `output_notebook`, but would keep `output_notebook`, right ? Otherwise without calling `output_notebook`, bokeh will display figure to file in zeppelin. That means I will still reply on `output_notebook` of bokeh. That's why I create `output_zeppelin` to avoid the the conflict with the `output_notebook` of bokeh in case users may call the right function.

**Comment by bryevdv** [comment]
>  I guess you will remove the parameter notebook_type in output_notebook, but would keep output_notebook, right ?

No I will leave the `notebook_type` but it will defer to the installed hook code, you need to supply the function that should be called, where I put `YOUR_OWN_LOAD_FUNCTION_BZKEP_HERE`

**Comment by bryevdv** [comment]
I just realized I forgot to update `output_notebook` to look up the code to call, in the earlier PR, which is probably a cause for confusion. But I will before the release.

**Comment by zjffdu** [comment]
Thanks, I will update bkzep after that

**Comment by bryevdv** [comment]
Actually if you can submit a PR to change the last line of `output_notebook` to do this:
```
 _run_notebook_hook(_state.notebook_type, 'load', resources, verbose, hide_banner, load_timeout)
```
instead of calling `load_notebook` directly, that would actually be a huge help, I am working on two big notebook regressions and not having to make a new branch/env would be a big time saver for me

(above code is untested but I think it's the right line)

**Comment by zjffdu** [comment]
Sure, I will do that.

**Comment by zjffdu** [comment]
@bryevdv I created bokeh https://github.com/bokeh/bokeh/pull/6811
and verify it in jupyter and zeppelin.
For zeppelin, user need to add the following extra 2 lines to make bokeh work in zeppelin.

```
import bkzep
output_notebook(notebook_type='zeppelin')
```

I call `install_notebook_hook` in `__init__.py`, so user need to explicitly call `import bkzep`, not sure whether this is a good practise for python.

**Comment by bryevdv** [comment]
brilliant, thank you I will get this merged tomorrow!

> not sure whether this is a good practise for python.

Seems ok to me
