### ISSUE TITLE
bkzep does not compatibile with bokeh 12.13 which has hidden notebook_content from bokeh.embed module.

### ISSUE THREAD

**Issue by markgong725** [zjffdu/bkzep#3]
Hi,

In bkzep/io.py, when bokeh later than "12.10" is used, you need to **import notebook_conent from bokeh.embed**.
However, in the latest **bokeh "12.13"**, the notebook_content function is not exposed by bokeh.embed module anymore (the notebook_content becomes an internal API function).
So, bkzep cannot work together with the latest bokeh release due to the exception "notebook_content is missing".
Please try to fix this compatibility issue as soon as possible.
Thank you!

**Comment by zjffdu** [comment]
Thanks for pointing that, will fix it asap

**Comment by zjffdu** [comment]
I have fixed that, please use bkzep 0.5.0
